### NumPy

In [139]:
import numpy as np
np.__version__

'2.2.0'

### Creating Numpy Arrays

In [140]:
list_1 = [1, 2, 3, 4, 5]
array = np.array(list_1)
print(array)

[1 2 3 4 5]


In [141]:
type(array)

numpy.ndarray

In [142]:
list_2 = [[3, 6, 7, 4],
         [3, 6, 8, 12]]
array_2 = np.array(list_2)
print(array_2)

[[ 3  6  7  4]
 [ 3  6  8 12]]


In [143]:
array_2.shape

(2, 4)

### Indexing 

In [144]:
array[2]

np.int64(3)

In [145]:
print(f"at (0,0) cell: {array_2[0, 0]} \nat (1, 2) cell: {array_2[1, 2]}")

at (0,0) cell: 3 
at (1, 2) cell: 8


In [146]:
array_3 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print(array_3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [147]:
array_3[:,2]

array([ 3,  7, 11, 15])

In [148]:
array_3[3, :]

array([13, 14, 15, 16])

### Changing Values

In [149]:
print(array)

[1 2 3 4 5]


In [150]:
array[2] = 99
print(array)

[ 1  2 99  4  5]


### Concat

In [151]:
print(array_2)

[[ 3  6  7  4]
 [ 3  6  8 12]]


In [152]:
array_21 = np.array([[13, 21, 43, 87],
                   [74, 86, 76, 94]])
np.concatenate([array_2, array_21], axis=0)

array([[ 3,  6,  7,  4],
       [ 3,  6,  8, 12],
       [13, 21, 43, 87],
       [74, 86, 76, 94]])

In [153]:
np.concatenate([array_2, array_21], axis=1)

array([[ 3,  6,  7,  4, 13, 21, 43, 87],
       [ 3,  6,  8, 12, 74, 86, 76, 94]])

### Resize

In [154]:
array_3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [155]:
array_3.reshape([8, 2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [156]:
array_3.reshape([2, 8])

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

### Multidimensional Arrays

In [157]:
array_4 = np.array([[[i*j+(k*i)+1 for i in range(5)] for j in range(4)] for k in range(3)])
array_4

array([[[ 1,  1,  1,  1,  1],
        [ 1,  2,  3,  4,  5],
        [ 1,  3,  5,  7,  9],
        [ 1,  4,  7, 10, 13]],

       [[ 1,  2,  3,  4,  5],
        [ 1,  3,  5,  7,  9],
        [ 1,  4,  7, 10, 13],
        [ 1,  5,  9, 13, 17]],

       [[ 1,  3,  5,  7,  9],
        [ 1,  4,  7, 10, 13],
        [ 1,  5,  9, 13, 17],
        [ 1,  6, 11, 16, 21]]])

In [158]:
array_4.shape

(3, 4, 5)

In [159]:
array_4[2, 2, 2]

np.int64(9)

In [160]:
array_4[:, :, 2]

array([[ 1,  3,  5,  7],
       [ 3,  5,  7,  9],
       [ 5,  7,  9, 11]])

### Arithmetic Functions

In [161]:
array_2

array([[ 3,  6,  7,  4],
       [ 3,  6,  8, 12]])

In [162]:
array_21

array([[13, 21, 43, 87],
       [74, 86, 76, 94]])

In [163]:
array_2 + array_21

array([[ 16,  27,  50,  91],
       [ 77,  92,  84, 106]])

In [164]:
array_2 * array_21 #element wise multiplication

array([[  39,  126,  301,  348],
       [ 222,  516,  608, 1128]])

In [165]:
array_2 / array_21

array([[0.23076923, 0.28571429, 0.1627907 , 0.04597701],
       [0.04054054, 0.06976744, 0.10526316, 0.12765957]])

In [166]:
array_2 * 2

array([[ 6, 12, 14,  8],
       [ 6, 12, 16, 24]])

In [167]:
array_3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [190]:
try:
    array_2 + array_3 
except ValueError:
    print("incompatible shapes")

incompatible shapes


In [169]:
array_2 ** 2

array([[  9,  36,  49,  16],
       [  9,  36,  64, 144]])

### Trig Functions

In [170]:
theta = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

In [171]:
sin = np.sin(theta)
sin

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [172]:
cos = np.cos(theta)
cos

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [173]:
tan = np.tan(theta)
tan

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

### Aggregations

In [174]:
array_21

array([[13, 21, 43, 87],
       [74, 86, 76, 94]])

In [175]:
np.sum(array_21)

np.int64(494)

In [176]:
np.prod(array_21)

np.int64(46432489809888)

In [177]:
np.mean(array_21)

np.float64(61.75)

In [178]:
np.std(array_21)

np.float64(29.596241315410307)

In [179]:
np.min(array_21)

np.int64(13)

In [180]:
np.max(array_21)

np.int64(94)

In [181]:
np.argmax(array_21)

np.int64(7)

In [182]:
np.argmin(array_21)

np.int64(0)

### Broadcasting

In [183]:
array_o = np.ones((3, 3))
array_o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [184]:
array_1 = np.array([1, 2, 3])
array_1

array([1, 2, 3])

In [185]:
array_o + array_1 # array_1 is broadcast to [[1, 2, 3],
                  #                          [1, 2, 3],
                  #                          [1, 2, 3]]

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [186]:
array_12 = np.arange(3)[:, np.newaxis]
array_12

array([[0],
       [1],
       [2]])

In [188]:
array_1 + array_12

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

### Boolean Masks

In [191]:
array_21

array([[13, 21, 43, 87],
       [74, 86, 76, 94]])

In [194]:
array_21 < 50

array([[ True,  True,  True, False],
       [False, False, False, False]])

In [195]:
array_21 == 94

array([[False, False, False, False],
       [False, False, False,  True]])

In [196]:
array_21[array_21 > 50]

array([87, 74, 86, 76, 94])

In [197]:
array_21[array_21 < 50]

array([13, 21, 43])

### Sorting

In [198]:
array

array([ 1,  2, 99,  4,  5])

In [199]:
np.sort(array)

array([ 1,  2,  4,  5, 99])

In [200]:
np.sort(array)[::-1]

array([99,  5,  4,  2,  1])